# Generated by Django 4.2.9 on 2025-04-20 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อลูกค้า')),
                ('address', models.TextField(verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทร')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'ใบแจ้งหนี้'), ('tax_invoice', 'ใบกำกับภาษี'), ('quotation', 'ใบเสนอราคา'), ('po', 'ใบสั่งซื้อ (PO)'), ('pr', 'ใบขอซื้อ (PR)')], default='invoice', max_length=20, verbose_name='ประเภทเอกสาร')),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True, verbose_name='เลขที่เอกสาร')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ออกเอกสาร')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='กำหนดชำระ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashboardUser.customer', verbose_name='ลูกค้า')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาขาย')),
                ('barcode', models.CharField(max_length=13, unique=True, verbose_name='บาร์โค้ด')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพสินค้า')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อผู้ออกบิล')),
                ('address', models.TextField(verbose_name='ที่อยู่ร้านค้า')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทร')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขประจำตัวผู้เสียภาษี')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='DashboardUser.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardUser.product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DashboardUser.seller', verbose_name='ผู้ออกบิล'),
        ),
    ]
