# Generated by Django 4.2.9 on 2025-04-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0014_alter_category_options_alter_product1_barcode_and_more'),
        ('DashboardUser', '0002_customer_invoice_product_seller_invoiceitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productapp.product1'),
        ),
    ]
