# Generated by Django 4.2.9 on 2025-04-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0004_invoiceitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='category',
        ),
    ]
