# Generated by Django 4.2.9 on 2025-04-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0005_remove_invoiceitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='Tax',
            field=models.PositiveIntegerField(default=0, verbose_name='Tax 7%'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='ลดราคา %'),
            preserve_default=False,
        ),
    ]
