# Generated by Django 4.2.9 on 2025-05-03 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0007_receipt_receiptitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
