# Generated by Django 4.2.9 on 2025-05-03 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0008_seller_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ออกเอกสาร'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
