# Generated by Django 4.2.9 on 2025-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0009_alter_invoice_date_alter_seller_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขประจำตัวผู้เสียภาษี'),
        ),
    ]
