# Generated by Django 4.2.9 on 2025-05-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardUser', '0010_customer_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='include_vat',
            field=models.BooleanField(default=False, verbose_name='รวม VAT'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='update_stock',
            field=models.BooleanField(default=False, verbose_name='อัพเดทสต็อก'),
        ),
    ]
