# Generated by Django 4.2.9 on 2025-04-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0013_alter_product1_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'ประเภทรายการสินค้า'},
        ),
        migrations.AlterField(
            model_name='product1',
            name='barcode',
            field=models.CharField(max_length=13, unique=True, verbose_name='บาร์โค้ด'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productapp.category', verbose_name='หมวดหมู่สินค้า'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มสินค้า'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='description',
            field=models.TextField(max_length=500, verbose_name='รายละเอียดสินค้า'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='image',
            field=models.ImageField(upload_to='product', verbose_name='รูปสินค้า'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='is_trending',
            field=models.BooleanField(default=False, verbose_name='สินค้าแนะนำ'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อสินค้า'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาขาย'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='profitprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคากำไร'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนในสต๊อก'),
        ),
        migrations.AlterField(
            model_name='product1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
    ]
